apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tfs-server-text-encoder
  name: tfs-server-text-encoder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tfs-server-text-encoder
  strategy: {}
  template:
    metadata:
      labels:
        app: tfs-server-text-encoder
    spec:
      nodeSelector:
        cloud.google.com/gke-accelerator: "nvidia-tesla-t4"
      containers:
      - image: gcr.io/gcp-ml-172005/tfs-sd-text-encoder:latest
        name: tfs-k8s-text-encoder
        imagePullPolicy: Always
        ports:
        - containerPort: 8500
          name: grpc
        - containerPort: 8501
          name: restapi
        resources:
          limits: 
            nvidia.com/gpu : "2"
          requests:
            cpu: "36"
            memory: "36Gi"
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: tfs-server-text-encoder
  name: tfs-server-text-encoder
spec:
  ports:
  - port: 8500
    protocol: TCP
    targetPort: 8500
    name: tf-serving-grpc
  - port: 8501
    protocol: TCP
    targetPort: 8501
    name: tf-serving-restapi
  selector:
    app: tfs-server-text-encoder
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tfs-server-diffusion-model
  name: tfs-server-diffusion-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tfs-server-diffusion-model
  strategy: {}
  template:
    metadata:
      labels:
        app: tfs-server-diffusion-model
    spec:
      nodeSelector:
        cloud.google.com/gke-accelerator: "nvidia-tesla-t4"
      containers:
      - image: gcr.io/gcp-ml-172005/tfs-sd-diffusion-model:latest
        name: tfs-k8s-diffusion-model
        imagePullPolicy: Always
        args: ["--rest_api_timeout_in_ms=1200000"]
        ports:
        - containerPort: 8500
          name: grpc
        - containerPort: 8501
          name: restapi
        resources:
          limits:
            nvidia.com/gpu: "1"
          requests:
            cpu: "18"
            memory: "18Gi"
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: tfs-server-diffusion-model-v2
  name: tfs-server-diffusion-model-v2
spec:
  ports:
  - port: 8500
    protocol: TCP
    targetPort: 8500
    name: tf-serving-grpc
  - port: 8501
    protocol: TCP
    targetPort: 8501
    name: tf-serving-restapi
  selector:
    app: tfs-server-diffusion-model-v2
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tfs-server-decoder
  name: tfs-server-decoder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tfs-server-decoder
  strategy: {}
  template:
    metadata:
      labels:
        app: tfs-server-decoder
    spec:
      nodeSelector:
        cloud.google.com/gke-accelerator: "nvidia-tesla-t4"
      containers:
      - image: gcr.io/gcp-ml-172005/tfs-sd-decoder:latest
        name: tfs-k8s-decoder
        imagePullPolicy: Always
        args: ["--rest_api_timeout_in_ms=1200000"]
        ports:
        - containerPort: 8500
          name: grpc
        - containerPort: 8501
          name: restapi
        resources:
          limits:
            nvidia.com/gpu: "1"
          requests:
            cpu: "18"
            memory: "18Gi"
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: tfs-server-decoder
  name: tfs-server-decoder
spec:
  ports:
  - port: 8500
    protocol: TCP
    targetPort: 8500
    name: tf-serving-grpc
  - port: 8501
    protocol: TCP
    targetPort: 8501
    name: tf-serving-restapi
  selector:
    app: tfs-server-decoder
  type: LoadBalancer
status:
  loadBalancer: {}