apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubFeatureMembership
metadata:
  name: gkehubfeaturemembership-gke-asia-southeast2
  namespace: config-control
spec:
  location: global
  membershipRef:
    name: gkehubmembership-gke-asia-southeast2
  featureRef:
    name: gkehubfeature-config-sync
  configmanagement:
    configSync:
      sourceFormat: unstructured
      git:
        syncRepo: "https://github.com/finiteloopme/tf-modules-argolis"
        syncBranch: "main"
        policyDir: "samples/config-controller-gke/app/stable-diffusion/all-in-one"
        syncWaitSecs: "20"
        syncRev: "HEAD"
        secretType: "none"
---
apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubMembership
metadata:
  name: gkehubmembership-gke-asia-southeast2
  namespace: config-control
spec:
  location: global
  description: GKE Hub Config Sync Membership for gke-asia-southeast2
  endpoint:
    gkeCluster:
      resourceRef:
        name: gke-asia-southeast2