apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fastapi-server
  name: fastapi-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-server
  strategy: {}
  template:
    metadata:
      labels:
        app: fastapi-server
    spec:
      nodeSelector:
        cloud.google.com/gke-accelerator: "nvidia-tesla-t4"
        # cloud.google.com/gke-accelerator: "nvidia-tesla-a100"
      containers:
      - image: gcr.io/gcp-ml-172005/sd-fastapi-allinone:latest
        name: fastapi-k8s
        ports:
        - containerPort: 80          
        resources:
          limits:
            nvidia.com/gpu: 2
          requests:
            cpu: "36"
            memory: "36Gi"
        env:
          - name: TF_FORCE_GPU_ALLOW_GROWTH
            value: "true"
